# Generated by Django 5.0.1 on 2024-02-03 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects_name', models.CharField(max_length=50)),
                ('subjects_code', models.IntegerField()),
                ('subjects_credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, null=True)),
                ('Age', models.FloatField()),
                ('Department', models.CharField(max_length=30, null=True)),
                ('Subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgpa_app.subjects_model')),
            ],
        ),
        migrations.CreateModel(
            name='Grade_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgpa_app.student_model')),
                ('student_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgpa_app.subjects_model')),
            ],
        ),
    ]
