# Generated by Django 5.0.1 on 2024-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_model',
            name='gender',
            field=models.CharField(choices=[('Others', 'Others'), ('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
    ]
