# Generated by Django 5.0.1 on 2024-02-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa_app', '0003_alter_student_model_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='Subjects',
        ),
        migrations.AlterField(
            model_name='student_model',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Others', 'Others'), ('Male', 'Male')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student_model',
            name='Subjects',
            field=models.ManyToManyField(to='cgpa_app.subjects_model'),
        ),
    ]
