# Generated by Django 5.0.1 on 2024-02-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa_app', '0004_remove_student_model_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_model',
            name='gender',
            field=models.CharField(choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], max_length=30, null=True),
        ),
    ]
