# Generated by Django 5.0.1 on 2024-02-04 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgpa_app', '0006_remove_grade_model_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade_model',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade_model',
            name='student_sub',
        ),
        migrations.AlterField(
            model_name='student_model',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='grade_model',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cgpa_app.student_model'),
        ),
        migrations.AddField(
            model_name='grade_model',
            name='student_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cgpa_app.subjects_model'),
        ),
    ]
